### ISSUE TITLE
Add support for Settings.machine.yml

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#1155]
Instead of always relying on develop.ontohub.org and staging.ontohub.org branches for machine-specific configs, we should have a specific file, which will be maintained by an admin.

**Comment by eugenk** [comment]
Do you want to have a specific file for
* the config as done in a5970def208bdace216c80f5af1b16c2577ff37b or
* machine specific settings like god worker count?

**Comment by 0robustus1** [comment]
both? :)

**Comment by eugenk** [comment]
Also allow to configure something that needs to be set in application.rb

**Comment by eugenk** [comment]
* git data directory should also be configurable per machine

**Comment by eugenk** [comment]
Why not simply use what already https://github.com/railsconfig/rails_config brings?
> Config entries are compiled from:
```
config/settings.yml
config/settings/#{environment}.yml
config/environments/#{environment}.yml
config/settings.local.yml
config/settings/#{environment}.local.yml
config/environments/#{environment}.local.yml
```
Settings defined in files that are lower in the list override settings higher.

The `settings*.local.yml` should be exactly what we are looking for. These files should be populated with the designated settings.

**Comment by jelmd** [comment]
Yes and no.

Yes wrt. use those and not another "scratching my head why ..." file.

No wrt. populate *.local.yml. These are exactly the file I expect to be machine specific/_private_, i.e. to be not part of the repo at all! As admin the first thing I would do is to add them to .gitignore!

And as said, settings.yml should just document all settings (config/application.rb should check and make sure, that the related Settings.* gets populated properly/with reasonable defaults if needed).

Don't torture the user with unecessary things/stuff he doesn't understand, but give him the option of being able to change things if needed, and don't torture yourself with overengineering things (i.e. AFAICS {#{environment}|settings}[.local].yml are rarely needed. One should avoid as much as possible to use them, because it makes it much harder to understand and tune the setup as needed...).

**Comment by eugenk** [comment]
> As admin the first thing I would do is to add them to .gitignore!

Yes, that's right. However, there are special cases, when we want them to be part of the repo: For example, the machine develop.ontohub.org uses only the branch develop.ontohub.org. We had a commit (a5970def208bdace216c80f5af1b16c2577ff37b) whose only purpose is to make this configuration. And this commit is only supposed to be on the branch develop.ontohub.org and not on any other branch.

I just changed this branch to use the *.local.* config files (force-added them) in order to have the default config files untouched. The relevant changes are:
* a4e41adf6a640938334b6ae29874dc8f0cbd2200
* 162fafa48f22c78965385bee9ccb84cd24959328

> And as said, settings.yml should just document all settings

I created #1242 for this.

**Comment by jelmd** [comment]
Sorry, but you response implies to me, that you still haven't had a closer look at the patch set or did not understand it or still haven't overcome your NIH attitude. Whatsoever, I've already all said what needs to be said wrt. this matter - any work on this seems to be a waste of time and thus sorry, I need to say, keep playing in the sandbox, keep developing chaotic and stone age like software, keep making you work as hard as possible and continue with such a rediculous src management, but without me - I have no time for such games.

**Comment by tillmo** [comment]
@jelmd, please remain constructive! Keep in mind that people having different backgrounds not always easily find a common language. Also please be more pragmatic towards reaching a workable solution.

**Comment by tillmo** [comment]
we now have settings.local.yml
