### ISSUE TITLE
Indefinitely pending ontology leads to enormous browser resource consumption

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1225]
This is related to indefinitely pending ontology in #1224. When opening its status page http://develop.ontohub.org/repositories/casl-um/ontologies/771/versions in a browser for a longer time, this leads to enormous resource consumption of both firefox and Chromium. Firefox also reports "script does not answer: assets/application.js:206"

**Comment by jelmd** [comment]
IMHO this is a general problem for ontohub pages. As soon as I switch on firebug, the browser becomes non-responding for a certain time (until the "script is not responding ...." message piops up). It seems that it doesn't matter, which ontohub page it is or whether there is a pending operation on the sever. My guess: the used framework (gwt/jquery?) stuff is buggy ...

**Comment by jelmd** [comment]
BTW: YSlow shows for  http://td.iws.cs.ovgu.de/
```
Grade F on Avoid HTTP 404 (Not Found) error

There are 70 requests that are 404 Not Found
```
All \*/assets/jquery.\*\?body=1

**Comment by tillmo** [comment]
the bad yslow performance is specific to your installation. There should be only one .*js file that is requested, namely /assets/application.js, and one *.css, namely /assets/application.css

**Comment by jelmd** [comment]
Well, that's not what I mean (I know, that there are some frameworks, which are smart enough to bundle the required stuff into a single "package" for prod mode ...). What I mean are 70 requests, which are than probably at least 70 (may be not so light) js requests to the package in prod mode, for a page, which AFAICS doesn't need any JS. So in short: checking the overhead might reveal some crazy things ...

BTW: IIRC (dealt with this stuff ~10+ years ago a little bit deeper), jquery was wrt. to modul. pretty dumb, but that might have been changed since MS joined this circle ;-)

**Comment by tillmo** [comment]
as I said, if ontohub is installed properly, there will be 1 (one) js request per page, not 70. Hence, we should have a closer look at what is going wrong at the td.iws.cs.ovgu.de installation.

**Comment by tillmo** [comment]
@jelmd, you need to call `rake assets:precompile`. Moreover, apache should serve these files, not rails.

**Comment by tillmo** [comment]
this side discussion should be continued at https://github.com/ontohub/admin-scripts/issues/4

**Comment by tillmo** [comment]
The source of the problem seems to be an exponential number of requests issued by the browser.

**Comment by ebolloff** [comment]
This isn't relevant anymore, I tested it on my machine.
