### ISSUE TITLE
wrong rewriting of ontohub into ta

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1461]
When I enter https://ontohub.org/meta/ into my browser, the address line gets rewritten into https://ta.iws.cs.ovgu.de//meta, and I have to approve the certificate (although I have already done that for ontohub.org)

**Comment by jelmd** [comment]
The root cause is:
```
    RewriteCond %{REQUEST_URI} .+/$
    RewriteRule ^(.+)/$ /$1 [R=301,L]
```
I took over this snippet from Bremen's httpd conf. For my taste it is odd, to let the httpd remove trailing slashes from URLs. Therefore I would like to remove the rule completely. If ontohub can't handle requests with trailing slashes, I need to make some more fine grained rules, which take server aliases into account ...

**Comment by tillmo** [comment]
works now
