### ISSUE TITLE
config Apache such that assets are served by Apache

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1501]
see http://www.concept47.com/austin_web_developer_blog/rails/how-to-try-out-puma-with-apache-proxy-right-now/

**Comment by jelmd** [comment]
Yepp, doing this since started with puma (~1 year ago). See /data/web/httpd/conf/sites/`uname -n`.* - main stuff is in the `<IfModule proxy_module>` section as well as ~ontohub/webapp/config/environments/production.rb (`config.serve_static_assets`).

The config.threadsafe part is not relevant, since MRI (i.e. non-threaded ruby) is used.

**Comment by tillmo** [comment]
sorry, I meant the stuff at the end of the page, under "the “correct” option: configure apache to bypass “/assets” and “/system” (by using “Location”)."

**Comment by jelmd** [comment]
No, the Location is not needed, since this is already covered by the ProxyPassMatch directive. It would be just overhead and make things more complicated. We have no `/system` in there, because this directory simply does not exist and thus there is nothing to serve [from it].

**Comment by tillmo** [comment]
OK, @jelmd has added `robots.txt` to the Apache config, so we could revert #1500

**Comment by SGraef** [comment]
pullrequest #1500 are not merged and issue #1490 are closed because the configure of @jelmd works i close this too
