### ISSUE TITLE
creating a new ontology version needs to be propagated

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#167]
... along all import links. That is, if O2 imports O1, and O1 is changed to a new version, the entities and sentences of O2 need to be recomputed, and a new version for O2 needs to be created.

**Comment by eugenk** [comment]
This needs to be tested. We think that it already works with the renewed parser, but we are not sure.

**Comment by eugenk** [comment]
@tillmo:
Is it possible to have a circular import graph with many files? For example:
* A imports B
* B imports A

where A and B are *in separate files*.

I know that CommonLogic's semantics support this, but Hets doesn't. How about other logics? Do we want to support it in Ontohub?

**Comment by tillmo** [comment]
Also OWL supports circular imports, also across many files. I think in Ontohub, we should not try to support circular imports for now. This could be a future feature, but not with very high priority.

**Comment by eugenk** [comment]
I just implemented this on branch 167-creating_a_new_ontology_version_needs_to_be_propagated. This is basically done. The feature works perfectly fine, but in order to write reasonable tests, I have to refactor the [AsyncHelper](https://github.com/ontohub/ontohub/blob/6d4ef892979ace580ed0a075609eb4acb3317209/config/initializers/async_helper.rb) and possibly the [Worker](https://github.com/ontohub/ontohub/blob/6d4ef892979ace580ed0a075609eb4acb3317209/lib/worker.rb).

The AsyncHelper was implemented to keep things DRY, but it also circumvents some testing mechanisms. It is not possible to use `Sidekiq::Testing.inline!` when `Sidekiq::Client.push ` is used as in the method [async_in](https://github.com/ontohub/ontohub/blob/6d4ef892979ace580ed0a075609eb4acb3317209/config/initializers/async_helper.rb#L25)

I suggest to remove the AsyncHelper completely and go with the best practices of Sidekiq, which is implementing a separate worker class for each use case.
