### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#635]
Back up the database and the repositories regularly. (I think that currently only the whole VM is backed up.)

**Comment by eugenk** [comment]
We can't run the script as admin user with `+`, because root has no access to ruby:

```
admin.tc ~ontohub/webapp > + script/backup create
/usr/bin/env: ruby: No such file or directory
```

**Comment by tillmo** [comment]
good, the script is there. However, is the script in fact used for a daily backup?

**Comment by eugenk** [comment]
I added the line
```
* 3 * * * + su - -c '~ontohub/webapp/script/backup create'
```
to admin's crontab on ontohub.org to create a backup every day at 03:00.

**Comment by tillmo** [comment]
@jelmd, the cronjob writes the db backup into ontohub's home folder. Is that folder covered by the general server backup?

**Comment by jelmd** [comment]
Well, deleted the cronjob after 3 days since it did nothing but spamming us with ~ 60 error mails/day.

Replaced it with 2 scripts, which properly integrate with the NetBackup client SW used on this machine, so that it touches the ~ontohub/maintenance.txt + dumps the DBs (~ 2.5..3x faster than with the ruby script) as part of the start hook and removes the ~ontohub/maintenance.txt when the backup is done. Thus no useless git repo duplication as well and the whole thing adheres to the "use least privilege" rule, i.e. sudo et. al. is not needed at all. 

DB dumps get stored below /data/psql/backup/dump.$N with N={0..6}, cycling.  Since this makes /data/psql/main/ redundant, it is now excluded from the backup (which also makes it get through much faster). 

**Rule of thumb**: Only /data/* alias /pool$n/* /etc/* and /var/* will make it into the backup.

Even there, certain stuff/noise gets excluded - for more details see `/etc/netbackup/exclude_list`

**Comment by eugenk** [comment]
> Well, deleted the cronjob after 3 days since it did nothing but spamming us with ~ 60 error mails/day.

Could you give us more information on the errors, please?

> Rule of thumb: Only /data/* alias /pool$n/* /etc/* and /var/* will make it into the backup.

Thanks, good to know.

**Comment by jelmd** [comment]
Did you try the command on the CLI? ;-)

**Comment by eugenk** [comment]
Yes, of course. If I haven't I wouldn't have put it into the crontab ;)

It ran perfectly fine. Now it doesn't because the backup target directory doesn't exist. How did it get deleted?

**Comment by jelmd** [comment]
You see - the environment should always be taken into account, i.e. you probably got facepalmed by dash and cron!

What cron under Ubuntu does, is running `/bin/sh -c $your_job` (and thus actually `/bin/dash -c $your_job`). So try e.g. `/bin/sh -c '+ su - -c /bin/ls'` and you should see the error message, which the crobjob above produced.

I guess, the dash doesn't behave posixly correct, and thus tries to consume __everything__ on the CLI starting with a dash ('-'). If it would work posixly correct, it should stop option parsing at the first argument, which doesn't start with a dash, which is '+'.

Anyway, since you asked: There is still a lot wrong with this thing:

1) Since Ubuntu cron follows POSIX, it just defines the env vars HOME=..., LOGNAME=..., PATH=/usr/bin:/bin , SHELL=/bin/sh and some shell internal vars. So even if there would be no dash  problem, you would hit something like 'command not found' because + is in /usr/sbin/. Also **note**, that cron does NOT source any .profile, .*rc or whatever shells usually do! It is expected, that the invoked cmd does it by itself, if needed!

2) The dash alone for su might cause trouble as well, since the man page explicitly states, that it "must be specified as the last su option"! A single dash is obscure enough to not use it in this context, since usually it indicates stdin or stdout and thus is confusing.

3) **Always** specify the user to su, even if it is optional. This makes it easy for anyone to see, what's going on and may avoid other problems.

4) **Always** put the '-c $cmd' at the end of the su cmd, i.e. right after the user! The '-c $cmd' option is a GNUish option and might be not found on other platforms like BSD/Solaris/etc.! So finally one should never use anything else than `su [-] [user [-c $cmd]]`

5) If a cronjob starts with +, su or sudo, it already smells and suggests reading the man pages again. If a cronjob should be executed by a certain user, it should be put in this user's crontab and **should not** be done in such a dirty way (and as you see, you actually shot yourself in the foot by doing so).

6) You specified a `*` in the minute field of the cronjob and thus it got executed each minute in the 3rd hour of the day!!! **60/h**,  ...

7) Another thing: the intention was probably to execute it as root. Why? There is **no need at all** to exec this script as root or even to exec sudo stuff in it again!

8) The machine gets a backup each day. So why to keep 365 copies of the DB as well as git repos on the HDD as well as on the backup media? I eventually understand DB copies for the last 3-7 days, but everything else doesn't make sense to me, is IMHO just a waste of valuable resources and actually costs really money, since backup SW, related maintenance contracts, devices, and media are not cheap at all! 

Counting all this together, in the past for this we would have withdrawn the permission to login/use the admin account/root privileges immediately to avoid further damage to the system!

So if you don't know, think twice, read the docs and if still not clear than **please ask**, especially if you are going to use superuser privileges!!!

Hint: The [Solaris Docs](http://docs.iws.cs.ovgu.de/admin/oracle-sun/solaris/solaris11.3/) - see Reference Manuals section - might be a little bit flavored, but usually they document available commands much better and even have proper examples! Reading on demand the man page there and than the man page on Linux should IMHO provide a much better understanding of the related cmd ...

PS: dirs get usually deleted by using `rm -rf ...` ;-)
